// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthUser struct {
	UserID uint64 `json:"user_id"`
}

type ChangePasswordReq struct {
	Code        string `json:"code"` // 验证码
	NewPassword string `json:"new_password"`
}

type CreateMomentReq struct {
	Type      uint8    `json:"type"`
	Content   string   `json:"content,optional"`
	ImageURLs []string `json:"image_urls,optional"`
	VideoURL  string   `json:"video_url,optional"`
}

type DeleteMomentReq struct {
	MomentID uint64 `json:"moment_id"`
}

type IPLocation struct {
	IP       string `json:"ip"`
	Country  string `json:"country"`
	Province string `json:"province"`
	City     string `json:"city"`
	ISP      string `json:"isp"`
	ISOCode  string `json:"iso_code"`
}

type LoginReq struct {
	Target   string `json:"target"`   // email or phone
	Channel  int32  `json:"channel"`  // 1: email, 2: phone
	Password string `json:"password"` // 密码
}

type LoginResp struct {
	Token    string   `json:"token"`
	UserInfo UserInfo `json:"user_info"`
}

type RegisterReq struct {
	Target   string `json:"target"`   // email or phone
	Channel  int32  `json:"channel"`  // 1: email, 2: phone
	Code     string `json:"code"`     // 验证码
	Password string `json:"password"` // 密码
}

type Response struct {
}

type SendVerificationCodeReq struct {
	Target  string `json:"target"`  // email or phone
	Channel int32  `json:"channel"` // 1: email, 2: phone
	Purpose int32  `json:"purpose"` // 1: registration, 2: password reset
}

type UpdateUserInfoReq struct {
	Username string `json:"username,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UserInfo struct {
	UserID    uint64 `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
	CreatedAt string `json:"created_at"`
}
