// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthUser struct {
	UserID uint64 `json:"user_id"`
}

type ChangePasswordReq struct {
	Code        string `json:"code"` // 验证码
	NewPassword string `json:"new_password"`
}

type CreateCommentReq struct {
	TargetType uint8  `json:"target_type"`
	TargetID   uint64 `json:"target_id"`
	FatherID   uint64 `json:"father_id,optional"`
	Content    string `json:"content"`
}

type CreateMomentReq struct {
	Type      uint8    `json:"type"`
	Content   string   `json:"content,optional"`
	ImageURLs []string `json:"image_urls,optional"`
	VideoURL  string   `json:"video_url,optional"`
}

type CreatorInfo struct {
	UserID uint64 `json:"user_id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
}

type DeleteCommentReq struct {
	CommentID uint64 `json:"comment_id"`
}

type DeleteMomentReq struct {
	MomentID uint64 `json:"moment_id"`
}

type GetMomentReq struct {
	MomentID uint64 `form:"moment_id"`
}

type GetMomentResp struct {
	Moment MomentInfo `json:"moment"`
}

type IPLocation struct {
	IP       string `json:"ip"`
	Country  string `json:"country"`
	Province string `json:"province"`
	City     string `json:"city"`
	ISP      string `json:"isp"`
	ISOCode  string `json:"iso_code"`
}

type ListMomentsReq struct {
	PageSize  uint32 `form:"page_size"`
	SortType  uint8  `form:"sort_type,optional"`
	PageToken string `form:"page_token,optional"`
}

type ListMomentsResp struct {
	Moments   []MomentInfo `json:"moments"`
	PageToken string       `json:"page_token"`
	HasMore   bool         `json:"has_more"`
}

type LoginReq struct {
	Target   string `json:"target"`   // email or phone
	Channel  int32  `json:"channel"`  // 1: email, 2: phone
	Password string `json:"password"` // 密码
}

type LoginResp struct {
	Token    string   `json:"token"`
	UserInfo UserInfo `json:"user_info"`
}

type MomentInfo struct {
	MomentID   uint64      `json:"moment_id"`
	CreatedAt  string      `json:"created_at"`
	UpdatedAt  string      `json:"updated_at"`
	Creator    CreatorInfo `json:"creator"`
	Type       uint8       `json:"type"`
	Content    string      `json:"content,optional"`
	VideoURL   string      `json:"video_url,optional"`
	ImageURLs  []string    `json:"image_urls,optional"`
	LikeNum    uint64      `json:"like_num"`
	CommentNum uint64      `json:"comment_num"`
	ShareNum   uint64      `json:"share_num"`
	ViewNum    uint64      `json:"view_num"`
	IsLiked    bool        `json:"is_liked"`
}

type MomentPageToken struct {
	PageToken
	HotScore float64 `json:"hot_score,optional"`
}

type PageToken struct {
	ID        uint64 `json:"id"`
	CreatedAt string `json:"created_at"` // 默认最新
	SortType  uint8  `json:"sort_type"`  // 1. 最新
}

type RegisterReq struct {
	Target   string `json:"target"`   // email or phone
	Channel  int32  `json:"channel"`  // 1: email, 2: phone
	Code     string `json:"code"`     // 验证码
	Password string `json:"password"` // 密码
}

type Response struct {
}

type SendVerificationCodeReq struct {
	Target  string `json:"target"`  // email or phone
	Channel int32  `json:"channel"` // 1: email, 2: phone
	Purpose int32  `json:"purpose"` // 1: registration, 2: password reset
}

type ToggleLikeReq struct {
	TargetType uint8  `json:"target_type"`
	TargetID   uint64 `json:"target_id"`
}

type ToggleLikeResp struct {
	Liked   bool   `json:"liked"`
	LikeNum uint64 `json:"like_num"`
}

type UpdateUserInfoReq struct {
	Username string `json:"username,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UserInfo struct {
	UserID    uint64 `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
	CreatedAt string `json:"created_at"`
}
