// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "github.com/luyb177/silent-sign-backend/internal/handler/auth"
	comment "github.com/luyb177/silent-sign-backend/internal/handler/comment"
	like "github.com/luyb177/silent-sign-backend/internal/handler/like"
	moment "github.com/luyb177/silent-sign-backend/internal/handler/moment"
	user "github.com/luyb177/silent-sign-backend/internal/handler/user"
	"github.com/luyb177/silent-sign-backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 登录账号
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: auth.LoginHandler(serverCtx),
				},
				{
					// 注册账号
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: auth.RegisterHandler(serverCtx),
				},
				{
					// 发送验证码
					Method:  http.MethodGet,
					Path:    "/send_code",
					Handler: auth.SendVerificationCodeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 创建评论
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: comment.CreateCommentHandler(serverCtx),
				},
				{
					// 删除评论
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: comment.DeleteCommentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/comment"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 点赞/取消点赞
					Method:  http.MethodPost,
					Path:    "/toggle",
					Handler: like.ToggleLikeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/like"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 创建动态
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: moment.CreateMomentHandler(serverCtx),
				},
				{
					// 删除动态
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: moment.DeleteMomentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/moment"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 修改密码
					Method:  http.MethodPost,
					Path:    "/change_password",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
				{
					// 修改用户信息
					Method:  http.MethodPut,
					Path:    "/update_info",
					Handler: user.UpdateUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)
}
