// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"
	"time"

	auth "github.com/luyb177/silent-sign-backend/internal/handler/auth"
	comment "github.com/luyb177/silent-sign-backend/internal/handler/comment"
	like "github.com/luyb177/silent-sign-backend/internal/handler/like"
	message "github.com/luyb177/silent-sign-backend/internal/handler/message"
	moment "github.com/luyb177/silent-sign-backend/internal/handler/moment"
	sse "github.com/luyb177/silent-sign-backend/internal/handler/sse"
	user "github.com/luyb177/silent-sign-backend/internal/handler/user"
	"github.com/luyb177/silent-sign-backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 登录账号
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: auth.LoginHandler(serverCtx),
				},
				{
					// 注册账号
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: auth.RegisterHandler(serverCtx),
				},
				{
					// 发送验证码
					Method:  http.MethodPost,
					Path:    "/send_code",
					Handler: auth.SendVerificationCodeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 创建评论
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: comment.CreateCommentHandler(serverCtx),
				},
				{
					// 删除评论
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: comment.DeleteCommentHandler(serverCtx),
				},
				{
					// 分页获取评论列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: comment.ListCommentsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/comment"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 点赞/取消点赞
					Method:  http.MethodPost,
					Path:    "/toggle",
					Handler: like.ToggleLikeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/like"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 消息列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: message.ListMessagesHandler(serverCtx),
				},
				{
					// 标记已读
					Method:  http.MethodPost,
					Path:    "/read",
					Handler: message.MarkReadHandler(serverCtx),
				},
				{
					// 发送消息
					Method:  http.MethodPost,
					Path:    "/send",
					Handler: message.SendMessageHandler(serverCtx),
				},
				{
					// 未读消息数
					Method:  http.MethodGet,
					Path:    "/unread_count",
					Handler: message.UnreadCountHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/message"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 创建动态
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: moment.CreateMomentHandler(serverCtx),
				},
				{
					// 删除动态
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: moment.DeleteMomentHandler(serverCtx),
				},
				{
					// 获取动态详情
					Method:  http.MethodGet,
					Path:    "/get",
					Handler: moment.GetMomentHandler(serverCtx),
				},
				{
					// 分页获取动态列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: moment.ListMomentsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/moment"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware},
			[]rest.Route{
				{
					// SSE 事件流
					Method:  http.MethodGet,
					Path:    "/events",
					Handler: sse.EventsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/sse"),
		rest.WithTimeout(0*time.Nanosecond),
		rest.WithSSE(),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTMiddleware, serverCtx.IPMiddleware},
			[]rest.Route{
				{
					// 修改密码
					Method:  http.MethodPost,
					Path:    "/change_password",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
				{
					// 修改用户信息
					Method:  http.MethodPost,
					Path:    "/update_info",
					Handler: user.UpdateUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)
}
